---
- include_tasks: init.yml
- include_tasks: server.yml
- include_tasks: dnsmasq.yml
- include_tasks: clients.yml
- include_tasks: iptables-chains.yml
- include_tasks: iptables-rules.yml network={{ item }}
  with_items: "{{ openvpn_networks }}"
- include_tasks: nginx.yml
  when: openvpn_manage_nginx_vhost == true
- include_tasks: dehydrated.yml
  when: openvpn_manage_dehydrated == true
