---
- name: restart nginx
  service:
    name: nginx
    state: restarted
- name: restart openvpn
  service:
    name: "openvpn-server@{{ openvpn_name }}"
    state: restarted
  notify: restart dnsmasq
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
